Send schedule using web socket
snu-quiqcl/artiq-proxy pull request #114
Opened 2024-01-04 07:08 UTC by BECATRUE

Now, a client i.e. IQUIP can fetch schedule using a web socket.

For test, run the code below.
```python
import json
from websockets.sync.client import connect

def main():
    uri = "ws://localhost:8000/schedule/"

    with connect(uri) as websocket:
        while True:
            response = websocket.recv()
            data = json.loads(response)
            print(data)

main()
```

Its result is the following.

![image](https://github.com/snu-quiqcl/artiq-proxy/assets/76851886/fdb7748d-0eac-4c5a-8d2c-30698f56c955)

This closes #113.

2024-01-10 13:49 UTC, kangz12345 requested changes
`WebSocket` looks so cool!

2024-01-10 13:49 UTC, kangz12345 commented on main.py
> +            await asyncio.wait_for(schedule_tracker.modifed.wait(), None)
Isn't it equivalent to:
```python
await schedule_tracker.modified.wait()
```

2024-01-11 07:30 UTC, BECATRUE commented on main.py
> +            await asyncio.wait_for(schedule_tracker.modifed.wait(), None)
Wow... Fantastic😮

2024-01-12 09:07 UTC, kangz12345 approved these changes
LGTM

2024-01-12 09:11 UTC, merged