Enable to set config file path when starting server
snu-quiqcl/artiq-proxy pull request #143
Opened 2024-04-11 03:55 UTC by BECATRUE

This closes #141.

Now, one can set the target config file path as follows:
```shell
$ CONFIG_PATH="config.json" ./server.sh           # target config file = "config.json"

$ CONFIG_PATH="config_template.json" ./server.sh  # target config file = "config_template.json"

$ ./server.sh                                     # target config file = default ("config.json")
```

The format looks a little weird, but it is the recommended method in FastAPI, so I applied this.

2024-04-11 23:49 UTC, kangz12345 commented
Great! `BaseSetting` would enable more flexible parameterization.
As you said, however, setting the environment variables is not familiar to our usual cases.
How about exploiting the shell script to make it as a command line argument?
In other words, for example,
```shell
./server.sh -c config.json
```
and for its implementation, [a Stack Overflow answer](https://unix.stackexchange.com/a/505342) may help.

2024-04-12 02:22 UTC, BECATRUE commented
I see! It looks much helpful. I will implement such the shell script.

2024-04-12 02:52 UTC, BECATRUE commented
Please check the updated `server.sh`! @kangz12345 
(The re-require button has been disabled😅)

2024-04-12 04:40 UTC, kangz12345 requested changes

2024-04-12 04:40 UTC, kangz12345 commented on server.sh
> +    python -m uvicorn main:app --host 0.0.0.0 --port 8000
How about defining variables for host address and port number in the shell script? For convenient modification of the script.

2024-04-12 05:06 UTC, kangz12345 approved these changes
LGTM!

2024-04-12 05:18 UTC, merged