Handle the scheduler options in submission
snu-quiqcl/artiq-proxy pull request #17
Opened 2023-06-26 01:16 UTC by BECATRUE

This PR will close #16.

First of all, please check and merget the PR #12.

I made the submission function able to handle the scheduler options; `pipeline`, `priority`, and `timed`.
You can test the submission using the following url.
```shell
http://127.0.0.1:8000/experiment/submit/?file=simple_simulation.py&args={%22color%22:%20%22r%22}&pipeline=main2&priority=0&timed=2023-06-26T09:53:00
```
Also, due to the encoding problem, please request the query in your browser such as Chrome or Safari, not `curl` command.

2023-06-26 05:07 UTC, kangz12345 requested changes

2023-06-26 05:07 UTC, kangz12345 commented on main.py
> +        priority: The priority that higher value means sooner scheduling.
"The priority that" can be omitted since the name of the argument already tells.

2023-06-26 05:07 UTC, kangz12345 commented on main.py
> +          If there is no due date, it is set to None.
Make description in the perspective of users' view. For example:
"None for no due date."

2023-07-07 04:12 UTC, kangz12345 requested changes

2023-07-07 04:12 UTC, kangz12345 commented on test.py
> +                directory = params.get('directory', '')
Duplicate `directory`.

2023-07-07 17:42 UTC, kangz12345 submitted a review, later dismissed
LGTM

2023-07-11 02:54 UTC, BECATRUE commented
Please re-check this PR! @kangz12345

2023-07-11 02:58 UTC, kangz12345 commented
Oh, I'm sorry. What do you mean by merge-base change? What has changed?

2023-07-13 03:54 UTC, BECATRUE commented
Umm.. I think I didn't do anything😂
According to [this discussion](https://github.com/orgs/community/discussions/58535), I think it is a minor bug and how about following the solution?

2023-07-13 05:00 UTC, kangz12345 submitted a review, later dismissed
LGTM

2023-07-13 05:00 UTC, kangz12345 submitted a review, later dismissed

2023-07-13 05:14 UTC, BECATRUE commented
The same problem occured.. I applied the solution in according the above link, please re-approve this😂 @kangz12345

2023-07-13 06:55 UTC, kangz12345 approved these changes, later dismissed

2023-07-13 06:57 UTC, kangz12345 approved these changes

2023-07-13 06:58 UTC, kangz12345 commented
The option (dismiss the stale review) was already disabled before.. 😅 
I enabled it and disabled it again, and now it works!

2023-07-14 00:29 UTC, merged