Sort the returns of `list_directory()`
snu-quiqcl/artiq-proxy pull request #28
Opened 2023-07-15 09:26 UTC by BECATRUE

This PR will close #13.

I sorted the returns of `list_directory()`.

1. List directories before files.
2. Sort alphabetically internally.

### Results
<img width="80%" src="https://github.com/snu-quiqcl/artiq-proxy/assets/76851886/bcf2a2ee-d642-4867-906c-46a304ab8036">

2023-07-15 09:27 UTC, BECATRUE commented
Also, I modified the format in `server.sh`.

2023-07-15 16:32 UTC, kangz12345 requested changes

2023-07-15 16:32 UTC, kangz12345 commented on main.py
> +        It lists directories before files, and is sorted alphabetically internally.
The second clause looks a little complicated. How about "... before files, sorted in an alphabetical order."

2023-07-17 03:21 UTC, kangz12345 approved these changes
LGTM

2023-07-19 21:31 UTC, merged