Turn on and off TTL switch of a specific DDS
snu-quiqcl/artiq-proxy pull request #83
Opened 2023-10-04 06:02 UTC by BECATRUE

This closes #82.

For a request, refer to the following command.
```shell
$ curl -X POST 'http://127.0.0.1:8000/dds/switch/?device=urukul0&channel=1&on=True'
```

2023-10-04 08:08 UTC, kangz12345 requested changes

2023-10-04 08:08 UTC, kangz12345 commented on main.py
> +async def set_dds_switch(device: str, channel: int, on: bool):
Please annotate the return type.

2023-10-04 08:13 UTC, kangz12345 commented on main.py
> +async def set_dds_switch(device: str, channel: int, on: bool):
Also please check the reviews in #84 as it has a similar structure.

2023-10-05 08:04 UTC, kangz12345 requested changes
Please push your work!

2023-10-05 08:39 UTC, BECATRUE commented
Oh, I now push my work! Thanks to notify me😃

2023-10-05 08:42 UTC, kangz12345 approved these changes
LGTM

2023-10-05 09:00 UTC, merged